[env]
VAULT_ADDR = "https://rnd.vault.0846e66f-a975-4a88-9e46-6dc6267e9b73.aws.hashicorp.cloud:8200"
VAULT_NAMESPACE = "admin"
HCP_ORGANIZATION_ID = "rnixon"
EDITOR = "nano"

[tools]
awscli = "latest"
"aqua:SuperCuber/dotter" = "latest"
github-cli = "latest"
go = "latest"
goreleaser = "latest"
jq = "latest"
node = "25.6.1"
terraform = "1.14.3"
vault = "1.21.2"
